### ISSUE TITLE
Inconsistent Column Count in Data Display

### ISSUE THREAD

**Issue by chrele** [ariefrahmansyah/remembergaza#4]
The number of data columns in the site is inconsistent.
<img width="1594" alt="Screenshot 2024-04-18 at 9 55 59 PM" src="https://github.com/ariefrahmansyah/remembergaza/assets/32842750/5b1f4dc2-b260-42dd-901e-23a8b3cd4030">
<img width="1459" alt="Screenshot 2024-04-18 at 9 56 12 PM" src="https://github.com/ariefrahmansyah/remembergaza/assets/32842750/29978098-bc7f-4cbc-b44e-d6555350b860">

**Comment by ariefrahmansyah** [comment]
Yup, the previous work on adding the flexbox is more as the groundwork. Are you willing to work on this, @chrele? I'll assign this card to you then.
cc: @msafdev

**Comment by ariefrahmansyah** [comment]
Assigned to @iamyuu
